#include<unistd.h>
#include<sys/types.h>
#include<sys/wait.h>
#include<sys/socket.h>
#include<sys/mman.h>
#include<sys/stat.h>
#include<netdb.h>
#include<errno.h>
#include<signal.h>
#include<stdlib.h>
#include<stdio.h>
#include<fcntl.h>
#include<string.h>
